Criando documento de Brainstorming
Requisitos-de-Software/2020.2-Telegram pull request #14
Opened 2021-03-10 19:21 UTC by alvesitalo

## Issue
Resolve #13 

## Descrição
Adiciona o documento Brainstorming da técnica de elicitação de requisitos.

2021-03-11 23:08 UTC, brendavsantos requested changes

2021-03-11 23:08 UTC, brendavsantos commented on docs/elicitacao/brainstorming.md
> +A sessão começa com uma pergunta que resume o objetivo de entender o que os usuátios querem e precisam, e pode ser conduzida em aproximadamente uma hora. Nela deve haver um moderador resposável por f
Erro de escrita, agora que o documento já foi criado relê ele pra ver se não tem mais nenhum errinho como esse, mas arruma o que tá nessa linha que eu aprovo (documento ficou ótimo).

2021-03-11 23:20 UTC, lboaventura25 commented
Revisado e padronizado, @alvesitalo  e @brendavsantos .
Muito boa a forma como a técnica foi descrita!!

2021-03-11 23:20 UTC, lboaventura25 approved these changes

2021-03-12 02:13 UTC, brendavsantos approved these changes

2021-03-12 02:13 UTC, merged